plugins {
    id 'com.android.application'
}

android {
    namespace 'com.garimpofood.scanner'
    compileSdk 35

    defaultConfig {
        applicationId "com.garimpofood.scanner"
        minSdk 26
        targetSdk 35
        versionCode 11
        versionName "0.7.2"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
